# Generated by Django 4.1.1 on 2022-09-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Burger',
            new_name='Burger1',
        ),
        migrations.RenameModel(
            old_name='Chicken',
            new_name='Chicken1',
        ),
    ]
