# Generated by Django 5.0.2 on 2024-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_chicken1_pricel_alter_chicken1_pricem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken1',
            name='estd',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
