# Generated by Django 5.0.2 on 2024-02-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
