# Generated by Django 5.0.2 on 2024-03-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_customuser_direccion_customuser_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken1',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
