# Generated by Django 5.0.2 on 2024-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_alter_steak1_pricel_alter_steak1_pricem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steak1',
            name='puntos',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
