# Generated by Django 5.0.2 on 2024-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_steak1_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken1',
            name='puntos',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
