# Generated by Django 5.0.2 on 2024-03-05 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0029_chicken1_puntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('comment', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.chicken1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
