# Generated by Django 5.0.2 on 2024-03-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0033_order1_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items1', to='food.order'),
        ),
    ]
