# Generated by Django 4.1.1 on 2022-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_burger_burger1_rename_chicken_chicken1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dImage', models.URLField()),
                ('loc', models.CharField(max_length=120)),
            ],
        ),
    ]
