# Generated by Django 5.0.2 on 2024-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken1',
            name='address',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chicken1',
            name='desc',
            field=models.CharField(default=23, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chicken1',
            name='tel',
            field=models.CharField(default=76, max_length=120),
            preserve_default=False,
        ),
    ]
