# Generated by Django 5.0.2 on 2024-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_chicken1_address_chicken1_desc_chicken1_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken1',
            name='priceL',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='chicken1',
            name='priceM',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
