# Generated by Django 5.0.2 on 2024-02-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_chicken1_lat_chicken1_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicken1',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='chicken1',
            name='lon',
        ),
    ]
