# Generated by Django 5.0.2 on 2024-02-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_remove_chicken1_lat_remove_chicken1_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken1',
            name='lat',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chicken1',
            name='lon',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
