# Generated by Django 5.0.2 on 2024-02-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_chicken1_lat_alter_chicken1_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken1',
            name='catg',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
